TARGET := iphone:clang:latest:7.0


include $(THEOS)/makefiles/common.mk

TWEAK_NAME = mutolaa-rickroll

mutolaa-rickroll_FILES = Tweak.x
mutolaa-rickroll_CFLAGS = -fobjc-arc

include $(THEOS_MAKE_PATH)/tweak.mk
